[package]
name = "kokedb-mysql-svc"
version.workspace = true
edition.workspace = true

[dependencies]
kokedb-common.workspace = true
kokedb-query.workspace = true
kokedb-cache.workspace = true
kokedb-meta.workspace = true

opensrv-mysql = "0.7.0"
tokio.workspace = true
async-trait.workspace = true

datafusion.workspace = true
log.workspace = true
thiserror.workspace = true
futures.workspace = true
sha1.workspace = true
chrono.workspace = true

[[bin]]
path = "src/main.rs"
name = "kokedb-mysql-svc"

[lints]
workspace = true
